### ISSUE TITLE
BundleUtilities failed to execute test program / libshared.so: cannot open shared

### ISSUE THREAD

**Issue by stepir** [theengs/gateway#23]
Hi

both `pip3 install TheengsGateway` and 

```
git clone https://github.com/theengs/gateway.git
cd gateway
git submodule update --init --recursive
python3 setup.py sdist
cd sdist
pip3 install distribution_file_name
```

fail with the following output:

```
            -- fixup_bundle: done
            Executing /tmp/pip-install-sfxts35u/cmake_a2a57f5668e04dd0b937e9b3bd3336a1/_skbuild/linux-aarch64-3.7/cmake-build/CMakeProject-build/Tests/BundleUtilities/testdir1/testbundleutils1 in /tmp/pip-install-sfxts35u/cmake_a2a57f5668e04dd0b937e9b3bd3336a1/_skbuild/linux-aarch64-3.7/cmake-build/CMakeProject-build/Tests/BundleUtilities/testdir1
            CMake Error at /tmp/pip-install-sfxts35u/cmake_a2a57f5668e04dd0b937e9b3bd3336a1/CMake-src/Tests/BundleUtilities/bundleutils.cmake:44 (message):
               failed to execute test program
      
      
              /tmp/pip-install-sfxts35u/cmake_a2a57f5668e04dd0b937e9b3bd3336a1/_skbuild/linux-aarch64-3.7/cmake-build/CMakeProject-build/Tests/BundleUtilities/testdir1/testbundleutils1:
              error while loading shared libraries: libshared.so: cannot open shared
              object file: No such file or directory
      
      
      
            make[5]: *** [CMakeFiles/testbundleutils1_test.dir/build.make:71: CMakeFiles/testbundleutils1_test] Error 1
            make[5]: Leaving directory '/tmp/pip-install-sfxts35u/cmake_a2a57f5668e04dd0b937e9b3bd3336a1/_skbuild/linux-aarch64-3.7/cmake-build/CMakeProject-build/Tests/BundleUtilities'
            make[4]: *** [CMakeFiles/Makefile2:231: CMakeFiles/testbundleutils1_test.dir/all] Error 2
            make[4]: Leaving directory '/tmp/pip-install-sfxts35u/cmake_a2a57f5668e04dd0b937e9b3bd3336a1/_skbuild/linux-aarch64-3.7/cmake-build/CMakeProject-build/Tests/BundleUtilities'
            make[3]: *** [Makefile:91: all] Error 2
            make[3]: Leaving directory '/tmp/pip-install-sfxts35u/cmake_a2a57f5668e04dd0b937e9b3bd3336a1/_skbuild/linux-aarch64-3.7/cmake-build/CMakeProject-build/Tests/BundleUtilities'
      
      
            108/625 Test  #80: CMakeDoubleProject ..........................................   Passed    2.83 sec
      
            99% tests passed, 1 tests failed out of 108
      
            Label Time Summary:
            CMake      =   0.00 sec*proc (0 test)
            CUDA       =  67.17 sec*proc (1 test)
            HIP        =   0.00 sec*proc (0 test)
            ISPC       =   0.00 sec*proc (0 test)
            Label1     =   0.00 sec*proc (0 test)
            Label2     =   0.00 sec*proc (0 test)
            command    =   0.00 sec*proc (0 test)
            policy     =   0.00 sec*proc (0 test)
            run        =   0.00 sec*proc (0 test)
      
            Total Test time (real) = 207.02 sec
      
            The following tests FAILED:
                 78 - BundleUtilities (Failed)
            Errors while running CTest
            make[2]: *** [CMakeFiles/CMakeProject-build.dir/build.make:126: CMakeProject-build-prefix/src/CMakeProject-build-stamp/CMakeProject-build-run_cmake_test_suite] Error 8
            make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/CMakeProject-build.dir/all] Error 2
            make: *** [Makefile:130: all] Error 2
              File "/tmp/pip-build-env-zu0bkmai/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
                cmkr.make(make_args, install_target=cmake_install_target, env=env)
              File "/tmp/pip-build-env-zu0bkmai/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 660, in make
                self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
              File "/tmp/pip-build-env-zu0bkmai/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 699, in make_impl
                os.path.abspath(CMAKE_BUILD_DIR()),
      
      
            --------------------------------------------------------------------------------
            -- Trying "Ninja" generator
            --------------------------------
            ---------------------------
            ----------------------
            -----------------
            ------------
            -------
            --
            --
            -------
            ------------
            -----------------
            ----------------------
            ---------------------------
            --------------------------------
            -- Trying "Ninja" generator - failure
            --------------------------------------------------------------------------------
      
      
      
            --------------------------------------------------------------------------------
            -- Trying "Unix Makefiles" generator
            --------------------------------
            ---------------------------
            ----------------------
            -----------------
            ------------
            -------
            --
            --
            -------
            ------------
            -----------------
            ----------------------
            ---------------------------
            --------------------------------
            -- Trying "Unix Makefiles" generator - success
            --------------------------------------------------------------------------------
      
            Configuring Project
              Working directory:
                /tmp/pip-install-sfxts35u/cmake_a2a57f5668e04dd0b937e9b3bd3336a1/_skbuild/linux-aarch64-3.7/cmake-build
              Command:
                cmake /tmp/pip-install-sfxts35u/cmake_a2a57f5668e04dd0b937e9b3bd3336a1 -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-sfxts35u/cmake_a2a57f5668e04dd0b937e9b3bd3336a1/_skbuild/linux-aarch64-3.7/cmake-install/src/cmake/data -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_VERSION_STRING:STRING=3.7.3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.7m -DPYTHON_LIBRARY:FILEPATH=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-zu0bkmai/overlay/lib/python3.7/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release
      
            Traceback (most recent call last):
      
            An error occurred while building with CMake.
              Command:
                cmake --build . --target install --config Release --
              Install target:
                install
              Source directory:
                /tmp/pip-install-sfxts35u/cmake_a2a57f5668e04dd0b937e9b3bd3336a1
              Working directory:
                /tmp/pip-install-sfxts35u/cmake_a2a57f5668e04dd0b937e9b3bd3336a1/_skbuild/linux-aarch64-3.7/cmake-build
            Please check the install target is valid and see CMake's output for more information.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cmake
        Building wheel for ninja (pyproject.toml): started
        Building wheel for ninja (pyproject.toml): still running...
        Building wheel for ninja (pyproject.toml): still running...
        Building wheel for ninja (pyproject.toml): still running...
        Building wheel for ninja (pyproject.toml): finished with status 'done'
        Created wheel for ninja: filename=ninja-1.10.2.3-cp37-cp37m-linux_aarch64.whl size=88283 sha256=18b210eda584185fb7ffdbc4bef591de04d8e8966f662438f561ecabfd29b337
        Stored in directory: /home/osmc/.cache/pip/wheels/5b/23/77/038bff02e4340bc5f6a25275d197654328a6f834b8801e7e13
      Successfully built ninja
      Failed to build cmake
      ERROR: Could not build wheels for cmake, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Can anyone help me understand why? I tried and was not able to find a solution....

Thanks

**Comment by 1technophile** [comment]
Hello,

Could you try also `pip install TheengsGateway`

Also are you installing with a regular user or with `root` access

**Comment by stepir** [comment]
hi @1technophile 

running with regular user, `root` access produce the following:

```
osmc@osmc:~$ sudo pip3 install -v TheengsGateway
Traceback (most recent call last):
  File "/home/osmc/.local/bin/pip3", line 6, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
```

`pip install -v TheengsGateway` produce the following:

```
osmc@osmc:~$ pip3 install -v TheengsGateway
Using pip 22.0.4 from /home/osmc/.local/lib/python3.7/site-packages/pip (python 3.7)
Defaulting to user installation because normal site-packages is not writeable
Collecting TheengsGateway
  Using cached TheengsGateway-0.1.5.tar.gz (118 kB)
  Running command pip subprocess to install build dependencies
  Collecting setuptools
    Using cached setuptools-62.1.0-py3-none-any.whl (1.1 MB)
  Collecting cmake
    Using cached cmake-3.22.4.tar.gz (31 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'

```
....
```
        The following tests FAILED:
             78 - BundleUtilities (Failed)
        Errors while running CTest
        make[2]: *** [CMakeFiles/CMakeProject-build.dir/build.make:126: CMakeProject-build-prefix/src/CMakeProject-build-stamp/CMakeProject-build-run_cmake_test_suite] Error 8
        make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/CMakeProject-build.dir/all] Error 2
        make: *** [Makefile:130: all] Error 2
          File "/tmp/pip-build-env-_v55udx8/overlay/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
            cmkr.make(make_args, install_target=cmake_install_target, env=env)
          File "/tmp/pip-build-env-_v55udx8/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 660, in make
            self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
          File "/tmp/pip-build-env-_v55udx8/overlay/lib/python3.7/site-packages/skbuild/cmaker.py", line 699, in make_impl
            os.path.abspath(CMAKE_BUILD_DIR()),


        --------------------------------------------------------------------------------
        -- Trying "Ninja" generator
        --------------------------------
        ---------------------------
        ----------------------
        -----------------
        ------------
        -------
        --
        --
        -------
        ------------
        -----------------
        ----------------------
        ---------------------------
        --------------------------------
        -- Trying "Ninja" generator - failure
        --------------------------------------------------------------------------------



        --------------------------------------------------------------------------------
        -- Trying "Unix Makefiles" generator
        --------------------------------
        ---------------------------
        ----------------------
        -----------------
        ------------
        -------
        --
        --
        -------
        ------------
        -----------------
        ----------------------
        ---------------------------
        --------------------------------
        -- Trying "Unix Makefiles" generator - success
        --------------------------------------------------------------------------------

        Configuring Project
          Working directory:
            /tmp/pip-install-t_sblf2l/cmake_8223058cd5e64c4e96507cae5df7a083/_skbuild/linux-aarch64-3.7/cmake-build
          Command:
            cmake /tmp/pip-install-t_sblf2l/cmake_8223058cd5e64c4e96507cae5df7a083 -G 'Unix Makefiles' -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-t_sblf2l/cmake_8223058cd5e64c4e96507cae5df7a083/_skbuild/linux-aarch64-3.7/cmake-install/src/cmake/data -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_VERSION_STRING:STRING=3.7.3 -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.7m -DPYTHON_LIBRARY:FILEPATH=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-_v55udx8/overlay/lib/python3.7/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release

        Traceback (most recent call last):

        An error occurred while building with CMake.
          Command:
            cmake --build . --target install --config Release --
          Install target:
            install
          Source directory:
            /tmp/pip-install-t_sblf2l/cmake_8223058cd5e64c4e96507cae5df7a083
          Working directory:
            /tmp/pip-install-t_sblf2l/cmake_8223058cd5e64c4e96507cae5df7a083/_skbuild/linux-aarch64-3.7/cmake-build
        Please check the install target is valid and see CMake's output for more information.
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for cmake
    Building wheel for ninja (pyproject.toml): started
    Building wheel for ninja (pyproject.toml): still running...
    Building wheel for ninja (pyproject.toml): still running...
    Building wheel for ninja (pyproject.toml): still running...
    Building wheel for ninja (pyproject.toml): finished with status 'done'
    Created wheel for ninja: filename=ninja-1.10.2.3-cp37-cp37m-linux_aarch64.whl size=88284 sha256=e4115af393d885d5c469a3b1be1a47d4c60be21dadbf8d6ca6f0f88400bdccf3
    Stored in directory: /home/osmc/.cache/pip/wheels/5b/23/77/038bff02e4340bc5f6a25275d197654328a6f834b8801e7e13
  Successfully built ninja
  Failed to build cmake
  ERROR: Could not build wheels for cmake, which is required to install pyproject.toml-based projects
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /tmp/pip-standalone-pip-oz_4alhw/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-j2llx5i6/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools cmake wheel scikit-build ninja
  cwd: [inherit]
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by 1technophile** [comment]
Hi,

Which OS and OS version do you have?

**Comment by stepir** [comment]
Hi

im running OSMC (4.9.113-64-osmc) https://osmc.tv/download/ ('sort' of raspbian) on a VERO4K https://osmc.tv/vero/ ('sort' of Pi4)

**Comment by stepir** [comment]
Hi,

I've built it on a Pi0 and worked immediately. As per the purpose of my testing I'm fine with it although long term I'd like to use my OSMC rather than another device.

I'll check with OSMC if they are available to help in supporting TheengsGateway and add eventually add it to their App Store.

If you have recommendation on why it's now working it's appreciated.

Thanks
