### ISSUE TITLE
Building wheel for cmake (pyproject.toml) did not run successfully

### ISSUE THREAD

**Issue by caffeineflo** [theengs/gateway#45]
**Describe the bug**
When trying to install theengsgateway through pip, either in a virtual env or with the system python, the installation fails.

I'm running arch linux on a Rapsberry Pi 4 and have installed cmake and ninja through pacman as well as having tried it without system wide installed cmake and ninja version.

Attaching the full error log to this ticket, but also highlighting the relevant bits here. Unfortunately I couldn't find much trying to search with these error messages myself which is why I'm hoping to get some help here.

[theengs-failed-install.log](https://github.com/theengs/gateway/files/9227186/theengs-failed-install.log)

```
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [1818 lines of output]
      Collecting setuptools
        Using cached setuptools-63.2.0-py3-none-any.whl (1.2 MB)
      Collecting cmake
        Using cached cmake-3.22.5.tar.gz (31 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting wheel
        Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      Collecting scikit-build
        Using cached scikit_build-0.15.0-py2.py3-none-any.whl (77 kB)
      Collecting ninja
        Using cached ninja-1.10.2.3-cp310-cp310-linux_armv7l.whl
      Collecting packaging
        Using cached packaging-21.3-py3-none-any.whl (40 kB)
      Collecting distro
        Using cached distro-1.7.0-py3-none-any.whl (20 kB)
      Collecting pyparsing!=3.0.5,>=2.0.2
        Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
      Building wheels for collected packages: cmake
        Building wheel for cmake (pyproject.toml): started
        Building wheel for cmake (pyproject.toml): still running...
        Building wheel for cmake (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for cmake (pyproject.toml) did not run successfully
```
a couple thousand lines in-between

```
           [666/1015] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmGeneratorTarget.cxx.o
            FAILED: Source/CMakeFiles/CMakeLib.dir/cmGeneratorTarget.cxx.o
            /usr/bin/c++ -DCURL_STATICLIB -DLIBARCHIVE_STATIC -D_FILE_OFFSET_BITS=64 -I/tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/_skbuild/linux-armv7l-3.10/cmake-build/CMakeProject-build/Utilities -I/tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/_skbuild/linux-armv7l-3.10/cmake-b
[theengs-failed-install.log](https://github.com/theengs/gateway/files/9227181/theengs-failed-install.log)
uild/CMakeProject-build/Source -I/tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/CMake-src/Source -I/tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/CMake-src/Source/LexerParser -I/tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/CMake-src/Source/CTest -I/tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/CMake-src/Source/CPack -isystem /tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/CMake-src/Utilities/std -isystem /tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/CMake-src/Utilities -O3 -DNDEBUG -std=c++17 -MD -MT Source/CMakeFiles/CMakeLib.dir/cmGeneratorTarget.cxx.o -MF Source/CMakeFiles/CMakeLib.dir/cmGeneratorTarget.cxx.o.d -o Source/CMakeFiles/CMakeLib.dir/cmGeneratorTarget.cxx.o -c /tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/CMake-src/Source/cmGeneratorTarget.cxx
            c++: fatal error: Killed signal terminated program cc1plus
            compilation terminated.
            [667/1015] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmMakefileExecutableTargetGenerator.cxx.o
            [668/1015] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmLocalUnixMakefileGenerator3.cxx.o
            [669/1015] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmMakefileTargetGenerator.cxx.o
            [670/1015] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmLocalGenerator.cxx.o
            [671/1015] Building CXX object Source/CMakeFiles/CMakeLib.dir/cmMakefile.cxx.o
            ninja: build stopped: subcommand failed.
            FAILED: CMakeProject-build-prefix/src/CMakeProject-build-stamp/CMakeProject-build-build /tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/_skbuild/linux-armv7l-3.10/cmake-build/CMakeProject-build-prefix/src/CMakeProject-build-stamp/CMakeProject-build-build
            cd /tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/_skbuild/linux-armv7l-3.10/cmake-build/CMakeProject-build && /usr/bin/cmake --build .
            ninja: build stopped: subcommand failed.
              File "/tmp/pip-build-env-mtxzx0mk/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
                cmkr.make(make_args, install_target=cmake_install_target, env=env)
              File "/tmp/pip-build-env-mtxzx0mk/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 680, in make
                self.make_impl(clargs=clargs, config=config, source_dir=source_dir, install_target=install_target, env=env)
              File "/tmp/pip-build-env-mtxzx0mk/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 704, in make_impl
                raise SKBuildError(
      
      
            --------------------------------------------------------------------------------
            -- Trying "Ninja" generator
            --------------------------------
            ---------------------------
            ----------------------
            -----------------
            ------------
            -------
            --
            --
            -------
            ------------
            -----------------
            ----------------------
            ---------------------------
            --------------------------------
            -- Trying "Ninja" generator - success
            --------------------------------------------------------------------------------
      
            Configuring Project
              Working directory:
                /tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/_skbuild/linux-armv7l-3.10/cmake-build
              Command:
                cmake /tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00 -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/_skbuild/linux-armv7l-3.10/cmake-install/src/cmake/data -DPYTHON_VERSION_STRING:STRING=3.10.5 -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/tmp/pip-build-env-mtxzx0mk/overlay/lib/python3.10/site-packages/skbuild/resources/cmake -DPython3_EXECUTABLE:FILEPATH=/dockerfs/theengsgateway/bin/python -DPython3_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython3_LIBRARY:PATH=/usr/lib/libpython3.10.so -DPython_EXECUTABLE:FILEPATH=/dockerfs/theengsgateway/bin/python -DPython_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPython_LIBRARY:PATH=/usr/lib/libpython3.10.so -DPYTHON_EXECUTABLE:FILEPATH=/dockerfs/theengsgateway/bin/python -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.10 -DPYTHON_LIBRARY:PATH=/usr/lib/libpython3.10.so -DCMAKE_BUILD_TYPE:STRING=Release
      
            Traceback (most recent call last):
      
            An error occurred while building with CMake.
              Command:
                cmake --build . --target install --config Release --
              Install target:
                install
              Source directory:
                /tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00
              Working directory:
                /tmp/pip-install-16g0i8nq/cmake_55f736eb3d2d43e3b5c0b1108ed69f00/_skbuild/linux-armv7l-3.10/cmake-build
            Please check the install target is valid and see CMake's output for more information.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cmake
      Failed to build cmake
      ERROR: Could not build wheels for cmake, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**To Reproduce**

Fresh Arch-Linux ARM installation. Install Python3 and run `sudo pip3 install TheengsGateway` 

**Expected behavior**

Successful installation

**Screenshots**
Not applicable

**Environment (please complete the following information):**

* Python 3.10.5
* pip 22.2.1 from /root/theengsgateway/lib/python3.10/site-packages/pip (python 3.10)

**Additional context**
n/a

* You should not have a compilation error if you use the versions of the libraries linked into the libraries folder, this badges show you the state of the compilation 
[![Build Status](https://github.com/theengs/decoder/workflows/Build/badge.svg?branch=development)](https://github.com/theengs/decoder/actions)
* If you are not sure this is a bug or an enhancement post your question to the forum
-> I'm mostly wondering since there is no build status if this might be a known compilation issue

**Comment by koenvervloesem** [comment]
Do you have a python3-skbuild package in Arch Linux? That did the trick for me in Ubuntu on the Raspberry Pi.

**Comment by caffeineflo** [comment]
> Do you have a python3-skbuild package in Arch Linux? That did the trick for me in Ubuntu on the Raspberry Pi.

Thanks for the fast reply, did you mean the [python-scikit-build](https://archlinux.org/packages/community/any/python-scikit-build/) package? 

In any case, testing now with that package installed, will report back!

**Comment by caffeineflo** [comment]
Same failure unfortunately with said package

**Comment by koenvervloesem** [comment]
And if you create the venv with the --system-site-packages option so it uses that package?

**Comment by koenvervloesem** [comment]
This is what I used to build the snap package, by the way. You could also try installing Theengs Gateway like this after installing snapd: https://github.com/theengs/gateway-snap

**Comment by caffeineflo** [comment]
Thank you!

I'll try that and report back. Looks like the issue is with cmake itself though as I tried replicating the steps in your GitHub workflow and trying to install cmake is what fails already. So definitely not with this package, but a dependency - anyways, will contribute back with a solution once I'm there

**Comment by caffeineflo** [comment]
I've been spending several more hours on this and the issue seems to be with Arch Linux and cmake not being able to be built on this rpi4. I can't tell if it's my installation that is messed up but I decided to use a x86_64 machine where the installation was done in 3 seconds. Closing this as it's unrelated to this project, thanks for the responses!

**Comment by maretodoric** [comment]
I need to add. There seems to be an issue with building cmake on certain platforms using python 3.10. Earlier versions (3.9 example) works fine.

**Comment by koenvervloesem** [comment]
Can you give the full error message you're getting? And on which platforms is that?

**Comment by phoolish** [comment]
FWIW I was able to get this working by upgrading pip (20.3.4 to 22.3)
