### ISSUE TITLE
Install error on Windows 10 (UnicodeDecodeError)

### ISSUE THREAD

**Issue by AndreOlt** [theengs/gateway#97]
Hi all,
I want to install the gateway on Windows 10.
I am using Windows 10 22H2 64-bit german and Python 3.11.2 64-bit.
The error is 'UnicodeDecodeError':

pip install TheengsGateway
Collecting TheengsGateway
  Using cached TheengsGateway-0.8.0.tar.gz (136 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Andre\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\Andre\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Andre\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\temp\pip-build-env-y5ly4cor\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\temp\pip-build-env-y5ly4cor\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\temp\pip-build-env-y5ly4cor\overlay\Lib\site-packages\setuptools\build_meta.py", line 485, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\temp\pip-build-env-y5ly4cor\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
        File "C:\Users\Andre\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1059, in read_text
          return f.read()
                 ^^^^^^^^
        File "C:\Users\Andre\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 2490: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

What can I do?
Thanks
Andre

**Comment by koenvervloesem** [comment]
Thanks for opening your issue. We forgot to set an explicit text encoding in the setup script, and because Windows uses cp1252 while the other operating systems use UTF-8 by default, this results in the error you're seeing. This is fixed in PR #98 and will be in the next Theengs Gateway release.
